#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
stages:
  - build
build:
  stage: build
  tags:
    - shell-runner
  script:
    - ./gradlew assemble
    - docker container rm -f spring_app || echo "d"
    - docker image rm -f spring-app || echo "d"
    - docker build -t spring-app:latest .
    - docker run -d -p 8081:8081 --name spring_app spring-app:latest
  only:
    - /^dev_[0-9]+(?:.[0-9]+)+$/ # regular expression
#deploy:
#  stage: deploy
#  tags:
#    - shell-runner
#  script:
#  only:
#    - develop
