#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
stages:
  - build
build:
  stage: build
  tags:
    - shell-runner
  script:
    - ./gradlew assemble
    - docker container rm -f spring_app-1 || echo "d"
    - docker image rm -f spring-app-1 || echo "d"
    - docker build -t spring-app-1:latest .
    - docker run -d -p 8085:8085 --name spring_app-1 spring-app-1:latest
  only:
    - /^dev_[0-9]+(?:.[0-9]+)+$/ # regular expression
#deploy:
#  stage: deploy
#  tags:
#    - shell-runner
#  script:
#  only:
#    - develop
