stages:
  - build
  - deploy
tags:
  - shell-runner
build:
  stage: build
  script:
    - ./gradlew assemble
#  only:
#    - master
deploy:
  stage: deploy
  script:
    - fuser -k 8081/tcp || echo "Kill Port"
    - nohup build/libs/SpringbootMarketplaceCy-0.0.1-SNAPSHOT.jar &
